In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
gdf_nodes = gpd.GeoDataFrame.from_file("../map/data/nodes.geojson")
gdf_nodes['lon'] = gdf_nodes.geometry.apply(lambda geom: geom.x)
gdf_nodes['lat'] = gdf_nodes.geometry.apply(lambda geom: geom.y)
    

df_from_to = pd.read_csv("../map/data/flows.csv")

In [3]:
gdf_nodes.head()
df_from_to.head()

      from_id       to_id    flow_type  value  unit
0     WIND-01  BATTERY-01  Electricity    NaN    kW
1    SOLAR-01  BATTERY-01  Electricity    NaN    kW
2  BATTERY-01     ELEC-01  Electricity    NaN    kW
3     ELEC-01     WWTP-01           O2    NaN  m3/h
4     WWTP-01     ELEC-01          H20    NaN  m3/h

In [4]:
src = gdf_nodes.rename(columns={"id": "from_id", "lon": "from_lon", "lat": "from_lat"})[["from_id", "from_lon", "from_lat"]]
dst = gdf_nodes.rename(columns={"id": "to_id",   "lon": "to_lon",   "lat": "to_lat"})[["to_id",   "to_lon",   "to_lat"]]

In [6]:
src.head()

      from_id  from_lon   from_lat
0  BATTERY-01  6.651082  52.365385
1    SOLAR-01  6.649967  52.364930
2     WIND-01  6.651262  52.365538
3   OFFICE-01  6.649580  52.364722
4     WWTP-01  6.650504  52.366173

In [7]:
df_from_to = df_from_to.merge(src, on="from_id", how="left").merge(dst, on="to_id", how="left")

In [8]:
df_from_to.head()

,from_id,to_id,flow_type,value,unit,from_lon,from_lat,to_lon,to_lat
0,WIND-01,BATTERY-01,Electricity,NaN,kW,6.651262,52.365538,6.651082,52.365385
1,SOLAR-01,BATTERY-01,Electricity,NaN,kW,6.649967,52.364930,6.651082,52.365385
2,BATTERY-01,ELEC-01,Electricity,NaN,kW,6.651082,52.365385,6.648985,52.364646
3,ELEC-01,WWTP-01,O2,NaN,m3/h,6.648985,52.364646,6.650504,52.366173
4,WWTP-01,ELEC-01,H20,NaN,m3/h,6.650504,52.366173,6.648985,52.364646

In [ ]:
COLOR_BY_TYPE = {
    "H2": [8, 104, 172],
    "O2": [102, 187, 106],
    "H2O": [38, 166, 154],
    "Heat": [251, 140, 0],
    "Electricity": [142, 36, 170]
}